services:
  vuejs:
    image: node:18
    container_name: ${VITE_PROJECT_NAME}_frontend
    user: "${MY_UID}:${GID}"
    working_dir: /vuejs
    volumes:
      - .:/vuejs
    ports:
      - "3000:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - app_networks
networks:
  app_networks:
    name: ${VITE_PROJECT_NAME}_network
    driver: bridge
