services:
  frontend:
    image: node:18
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - app_networks
networks:
  app_networks:
    name: backend_network
    driver: bridge
