services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${PROJECT_NAME}_app
    volumes:
      - .:/var/www/html
      - ./docker/php/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - app_networks
    command: >
      /bin/sh -c "cd .. &&
                  composer config name ${COMPOSER_PROJECT_NAME} &&
                  composer config type ${COMPOSER_TYPE} &&
                  apache2-foreground" 
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_networks
  # composer:
  #   image: composer:2
  #   container_name: composer
  #   working_dir: /var/www/html
  #   user: "1000:1000"
  #   volumes:
  #     - .:/var/www/html
  #   entrypoint: /bin/bash
  #   command:
  #     - -c
  #     - |
  #       if [ ! -f artisan ]; then
  #         composer install && \
  #         composer config name ${COMPOSER_PROJECT_NAME} && \
  #         composer config type ${COMPOSER_TYPE}
  #       fi  

volumes:
  db_data:

networks:
  app_networks:
    name: backend_network
    driver: bridge