services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${MY_UID}
        GID: ${GID}
    container_name: ${PROJECT_NAME}_backend
    volumes:
      - .:/var/www/html
      - ./docker/php/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - app_networks
    command: >
      /bin/sh -c "cd .. &&
                  composer config name ${COMPOSER_PROJECT_NAME} &&
                  composer config type ${COMPOSER_TYPE} &&
                  composer install &&
                  apache2-foreground" 
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_networks

volumes:
  db_data:

networks:
  app_networks:
    name: ${PROJECT_NAME}_network
    driver: bridge